name: Docker (dev) - Build & Publish
on:
  workflow_dispatch:
  push:
    branches:
     - master
jobs:
  build:
    uses: nuvigant/actions/.github/workflows/docker-build-and-push.yml@master
    with:
      tag: dev
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
