name: Docker (dev) - Build & Publish
on:
  workflow_dispatch:
  push:
    branches:
     - master
jobs:
  build:
    uses: nuvigant/actions/.github/workflows/docker-build-and-push.yml@master
    with:
      tag: dev
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
