on:
  workflow_call:
    inputs:
      image:
        description: 'Image Name'
          required: true
          type: string
        dockerfile:
          description: 'Dockerfile Name or Path'
          default: 'Dockerfile'
          required: false
          type: string
    
  jobs:
    build-container:
      name: DockerHub Login and Push
      runs-on: ubuntu-latest
      steps: 
      
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Docker Build and Push (dev)
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ inputs.dockerfile }}
          tags: nuvigantadmin/${{ inputs.image }}:${GITHUB_REF##*/}
