on:
  workflow_call:
    inputs:
      branch:
        description: 'Repository Branch'
        required: true
        type: string
      image:
        description: 'Image Name'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile Name or Path'
        default: 'Dockerfile'
        required: false
        type: string
    secrets:
      username: 
        required: true
      password:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:
  slack-notification-start:
    name: Notify Start on Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Start Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: GitHubot 
        SLACK_ICON: "https://img.icons8.com/material-outlined/128/000000/github.png"
        SLACK_TITLE: "${{ github.event.repository.name }} - #${{ github.run_number }} ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}"
        SLACK_COLOR: '#007acc'
        SLACK_MESSAGE: 'Trabajo iniciando.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  build-container:
    name: DockerHub Login and Push
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Docker Build and Push (${{ inputs.branch }})
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ${{ inputs.dockerfile }}
        tags: ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}
  slack-notification-start:
    name: Notify Finish on Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Success Notification
      if: ${{ job.status == 'success' }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: GitHubot 
        SLACK_ICON: "https://img.icons8.com/material-outlined/128/000000/github.png"
        SLACK_TITLE: "${{ github.event.repository.name }} - #${{ github.run_number }} ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}"
        SLACK_COLOR: 'good'
        SLACK_MESSAGE: 'Trabajo finalizado con éxito.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    - name: Slack Failure Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: GitHubot 
        SLACK_ICON: "https://img.icons8.com/material-outlined/128/000000/github.png"
        SLACK_TITLE: "${{ github.event.repository.name }} - #${{ github.run_number }} ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}"
        SLACK_COLOR: 'bad'
        SLACK_MESSAGE: 'El trabajo falló.'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
