on:
  workflow_call:
    inputs:
      branch:
        description: 'Repository Branch'
        required: true
        type: string
      image:
        description: 'Image Name'
        required: true
        type: string
      dockerfile:
        description: 'Dockerfile Name or Path'
        default: 'Dockerfile'
        required: false
        type: string
    secrets:
      username: 
        required: true
      password:
        required: true
      SLACK_WEBHOOK:
        required: true
jobs:
  slack-notification:
    name: Notify Start on Slack
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_TITLE: "${{ github.event.repository.name }} - #${{ github.run_number }} ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}"
        SLACK_COLOR: '#36bb8b'
        SLACK_MESSAGE: 'Inicio de compilación. Cambios por ${{ github.event.pusher.name }}'
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  build-container:
    name: DockerHub Login and Push
    runs-on: ubuntu-latest
    steps: 
    - name: Docker Login
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Docker Build and Push (${{ inputs.branch }})
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        file: ${{ inputs.dockerfile }}
        tags: ${{ secrets.username }}/${{ inputs.image }}:${{ inputs.branch }}
